# Generated by Django 4.2.3 on 2023-07-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1990-01-13'),
            preserve_default=False,
        ),
    ]
